import {
  Accessibility,
  Activity,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightToLine,
  ArrowUp,
  BarChart3,
  BadgeCheck,
  Bell,
  BellOff,
  Bookmark,
  BookmarkCheck,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleOff,
  CircleUser,
  Clipboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Copy,
  CreditCard,
  Download,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  FileCog,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  Forward,
  Fullscreen,
  Grid2x2,
  Heart,
  HeartOff,
  HelpCircle,
  Image,
  Info,
  KeyRound,
  Keyboard,
  Languages,
  Laptop,
  Link,
  List,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Mouse,
  Move,
  Navigation,
  Package,
  Pause,
  Pencil,
  Phone,
  PhoneCall,
  Play,
  Plus,
  Radio,
  Receipt,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  StarOff,
  Store,
  Tablet,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Unlock,
  Upload,
  User,
  Users,
  Video,
  Volume1,
  Volume2,
  VolumeX,
  Wrench,
  X,
  XCircle,
  Zap
} from '@tamagui/lucide-icons'

export const ICONS = {
  // Navigation
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  arrow_back_ios: ArrowLeft,
  arrow_forward_ios: ArrowRight,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  first_page: ArrowLeftToLine,
  last_page: ArrowRightToLine,
  home: Navigation,
  menu: Menu,
  close: X,

  // Actions
  add: Plus,
  remove: Minus,
  check: Check,
  done: Check,
  edit: Pencil,
  delete: Trash2,
  save: Save,
  cancel: X,
  refresh: RefreshCw,
  search: Search,
  filter_list: Filter,
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  settings: Settings,
  build: Wrench,

  // Communication
  mail: Mail,
  email: Mail,
  send: Send,
  chat: MessageCircle,
  forum: MessageCircle,
  comment: MessageCircle,
  notifications: Bell,
  notifications_none: BellOff,
  phone: Phone,
  call: PhoneCall,
  contacts: Users,
  person: User,
  group: User,
  groups: Users,

  // Media
  play_arrow: Play,
  pause: Pause,
  stop: CircleOff,
  skip_next: ArrowRight,
  skip_previous: ArrowLeft,
  fast_forward: Forward,
  fast_rewind: ArrowLeft,
  volume_up: Volume2,
  volume_down: Volume1,
  volume_off: VolumeX,
  mic: Mic,
  mic_off: MicOff,
  image: Image,
  photo: Image,
  movie: Video,
  music_note: Activity,
  camera_alt: Camera,
  videocam: Video,

  // Files
  folder: Folder,
  folder_open: FolderOpen,
  file_copy: FileCog,
  description: FileText,
  attachment: Link,
  upload_file: Upload,
  download: Download,
  cloud: Cloud,
  cloud_upload: CloudUpload,
  cloud_download: CloudDownload,
  picture_as_pdf: FileText,

  // Shopping
  shopping_cart: ShoppingCart,
  shopping_bag: ShoppingBag,
  store: Store,
  local_shipping: Package,
  credit_card: CreditCard,
  payments: CreditCard,
  receipt: Receipt,
  sell: ShoppingBag,
  inventory_2: Package,

  // Status
  info: Info,
  help: HelpCircle,
  warning: AlertTriangle,
  error: XCircle,
  check_circle: CheckCircle,
  block: CircleOff,
  verified: BadgeCheck,
  priority_high: AlertCircle,
  report: AlertTriangle,

  // Security
  lock: Lock,
  lock_open: LockOpen,
  key: KeyRound,
  security: Shield,
  visibility: Eye,
  visibility_off: EyeOff,
  fingerprint: Accessibility,
  password: KeyRound,

  // Devices
  phone_android: Smartphone,
  phone_iphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  computer: Monitor,
  desktop_windows: Monitor,
  keyboard: Keyboard,
  mouse: Mouse,
  watch: Timer,
  smartphone: Smartphone,

  // Time
  schedule: Clock,
  access_time: Clock,
  calendar_today: Calendar,
  event: CalendarDays,
  today: Calendar,
  date_range: CalendarDays,
  alarm: AlarmClock,
  timer: Timer,

  // Location
  location_on: MapPin,
  location_off: MapPin,
  place: MapPin,
  map: Map,
  navigation: Navigation,
  public: Languages,
  language: Languages,
  explore: Navigation,

  // Content
  star: Star,
  star_border: StarOff,
  favorite: Heart,
  favorite_border: HeartOff,
  bookmark: Bookmark,
  bookmark_border: BookmarkCheck,
  flag: Flag,
  label: Bookmark,
  link: Link,
  open_in_new: ExternalLink,
  share: Share2,
  copy_all: Copy,

  // UI
  check_box: CheckSquare,
  check_box_outline_blank: CheckSquare,
  radio_button_checked: Radio,
  radio_button_unchecked: Radio,
  toggle_on: Zap,
  toggle_off: Zap,
  drag_handle: Move,
  view_list: List,
  grid_view: Grid2x2,
  dashboard: Grid2x2,
  fullscreen: Fullscreen,

  // Business
  work: Clipboard,
  business: Building2,
  account_balance: Building2,
  analytics: BarChart3,
  bar_chart: BarChart3,
  pie_chart: BarChart3,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  attach_money: CreditCard,
  euro: Euro,

  // Authentication
  login: LogIn,
  logout: LogOut,

  // User
  account_circle: CircleUser,

  // Accessibility / utility
  accessibility: Accessibility,
  code: Code,
  archive: Archive,
  unlock: Unlock
} as const
